### ISSUE TITLE
Big endian systems

### ISSUE THREAD

**Issue by mattip** [eloj/radix-sorting#1]
How would this code deal with big-endian systems like powerpc? It seems the key computation uses shifts, could they use multiplication instead?

**Comment by eloj** [comment]
Using multiplication instead of shifts doesn't give you anything when it comes to endianess.

I haven't used a big-endian machine in many decades, and they're becoming increasingly rare, but I don't see how it would change anything. The basic algorithm loads, manipulates and stores unsigned integers; the underlying byte-order should be irrelevant.

Where I could see a problem is when casting memory, as is done in the C++ code when manipulating floats, but I think in this case we're good there too.

I should add a paragraph on that, but I'd really need to try it on a machine to not get the details wrong though.
