### ISSUE TITLE
MSD radix sort

### ISSUE THREAD

**Issue by KirillLykov** [eloj/radix-sorting#4]
Forgive me for using issues to contact you. Just saw that you are also experimenting with radix sort and wanted to share my results: https://github.com/KirillLykov/int-sort-bmk
I've implemented MSD and hybrid MSD/LSD where LSD is by Travis Downs (https://github.com/travisdowns/sort-bench)
Plus I did some benchmarks different distributions, plots with maplotlib -- might be reusable. 
If you would be interested on collaborating on this effort -- please write me to email (`<surname>.<name>@gmail.com`).

**Comment by eloj** [comment]
I appreciate the interest, but I sort of like going at it by myself and on my own pace.

Not super-surprised hybrid doesn't really perform. I have a rough idea to mark off used 'buckets' in a bitmap, and iterate the bitmap instead of 0..RADIX_SIZE-1, in the hope of lowering the 'fixed overhead'. But that's just that, a rough idea.

(I did see that you are using Travis "is_trivial", which I can't think is better than the [direct probe I suggest](https://github.com/eloj/radix-sorting#column-skipping))
